name: PawRescue CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # --- BACKEND CI ---
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: rm -rf node_modules package-lock.json
      - run: npm ci || npm install
      # - run: npm run lint
      - run: npm run test

  # --- FRONTEND (FLUTTER) CI ---
  mobile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Verificar si existe la carpeta mobile
      - name: Check if mobile folder exists
        id: check
        run: |
          if [ -d "mobile" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - uses: subosito/flutter-action@v2
        if: steps.check.outputs.exists == 'true'
        with:
          flutter-version: '3.x'
          channel: 'stable'
      
      - run: flutter pub get
        if: steps.check.outputs.exists == 'true'
        working-directory: ./mobile
        
      - run: flutter analyze
        if: steps.check.outputs.exists == 'true'
        working-directory: ./mobile
        
      - run: flutter test
        if: steps.check.outputs.exists == 'true'
        working-directory: ./mobile
